"""Constantes jobs planifiés."""

DAILY_ANALYSIS_RUN_TYPE = "DAILY_ANALYSIS"
FINAL_ANALYSIS_RUN_TYPE = "FINAL_ANALYSIS"
RESULTS_COLLECTION_RUN_TYPE = "RESULTS_COLLECTION"
SETTLEMENT_RUN_TYPE = "SETTLEMENT"
MAINTENANCE_RUN_TYPE = "MAINTENANCE"

JOB_DAILY_ANALYSIS = "daily_analysis"
JOB_FINAL_ANALYSIS = "final_analysis"
JOB_RESULTS_COLLECTION = "results_collection"
JOB_SETTLEMENT = "settlement"
JOB_SUBSCRIPTION_EXPIRATION = "subscription_expiration"
JOB_MAINTENANCE = "maintenance"

ALL_JOBS = (
    JOB_DAILY_ANALYSIS,
    JOB_FINAL_ANALYSIS,
    JOB_RESULTS_COLLECTION,
    JOB_SETTLEMENT,
    JOB_SUBSCRIPTION_EXPIRATION,
    JOB_MAINTENANCE,
)
